version: 1.0.{build}
skip_tags: true
os: Windows Server 2012 R2
branches:
  only:
    - master
before_build:
  - git submodule update --init --recursive
  - .\prepare.bat
  - .\.nuget\nuget.exe restore SharpSnmpLib.Classic.sln
build:
  project: SharpSnmpLib.Classic.sln
  verbosity: minimal
